### ISSUE TITLE
Different Fisher's C and AIC values when changing order of regression models

### ISSUE THREAD

**Issue by ElisaVanCleemput** [jslefche/piecewiseSEM#189]
Hi!

I get different Fisher's C and AIC outcomes when I change the order of the individual regression models in my SEM. 

I don't know if it is relevant, but my model encompasses an interaction effect between a numerical (invasion %) and categorical variable (species identity, 2 levels), which we included in the sem by introducing a dummy variable: species2 (0 or 1). The numerical variable "invasion%" was split up in invasion_sp1 and invasion_sp2.

Conceptually, my model looks as follows:
psem(
lme(var1 ~ species2 + invasion_sp1 + invasion_sp2, random = ~1|site, data=data), 
lme(var2 ~ species2 + invasion_sp1 + invasion_sp2, random = ~1|site, data=data), 
lme(var3 ~ species2 + invasion_sp1 + invasion_sp2, random = ~1|site, data=data), 
lme(var4 ~ species2 + invasion_sp1 + invasion_sp2, random = ~1|site, data=data), 
lme(var5 ~ species2 + invasion_sp1 + invasion_sp2, random = ~1|site, data=data),
lme(var6 ~ species2 + invasion_sp1 + invasion_sp2 + var1 + var2 + var3 + var4 + var5 , random = ~1|site, data=data))

When I change the order of the individual lines, e.g. put the line specifying var1 after var5, the estimates and significance of the coefficients remain the same. However, the value and significance of Fisher’s C, and the value of AIC change. This has huge consequences for interpreting the goodness-of-fit of the model.

How can I fix this problem? Thanks!

**Comment by jslefche** [comment]
Hi Elisa, please try installing the development version. I believe this bug has been fixed there: https://github.com/jslefche/piecewiseSEM/tree/devel

If it persists please let me know!

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by ElisaVanCleemput** [comment]
Hi Jonathan,

Thanks for the quick reply! Unfortunately the problem was not solved when using the development version.

Elisa

**Comment by jslefche** [comment]
Hi Elisa,

I was able to reproduce this. Unfortunately, its not a bug, but a deeper issue with the use of mixed effects models in SEM. In short, the order of the models determines the order of the independence claims. Normally, this shouldn’t matter (eg x1 | x2 is the same as x2 | x1 in terms of the P-value) UNTIL mixed effects come into play, which yield different P-values.

I’ve put out a few emails and will let you know if we are able to reach a consensus on a path forward.

In the interim, I advise identifying the independence claims using `basisSet` and then determining the proper order (if it matters) and supplying this revised basis set directly to `dSep`  . Let me know if you need a hand with this

Cheers,

Jon

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net

**Comment by jslefche** [comment]
This should be fixed with the new method by Douma and Shipley, see `LLchisq`
